---
- name: upgrade all packages
  yum: name=* state=latest
  
- name: Add rpm key 
  rpm_key: state=present key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
  
- name: Copy file 
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo  