---
- name: install elasticsearch
  yum: name=elasticsearch state=latest
  
- name: Add elasticsearch paths to configuration  
  lineinfile: dest={{ homeDir }}/bin/elasticsearch.in.sh regexp='ES_JAVA_OPTS' line='ES_JAVA_OPTS="-Des.config={{ configDir }}/elasticsearch.yml -Des.path.conf={{ configDir }}/ -Des.path.home={{ homeDir }} -Des.path.logs={{ logDir }} -Des.path.data={{ dataDir}} -Des.path.work={{ tmpDir }} -Des.path.plugins={{ homeDir }}/plugins"'
  
- name: Register service
  command: /sbin/chkconfig --add elasticsearch

- name: Restart Elasticsearch
  service: name=elasticsearch state=restarted