---
- name: install elasticsearch
  yum: name=elasticsearch state=latest
  
- name: Add elasticsearch paths to configuration  
  lineinfile: dest={{ homeDir }}/bin/elasticsearch.in.sh regexp='ES_JAVA_OPTS' line='ES_JAVA_OPTS="-Des.config={{ configDir }}/elasticsearch.yml -Des.path.conf={{ configDir }}/ -Des.path.home={{ homeDir }} -Des.path.logs={{ logDir }} -Des.path.data={{ dataDir}} -Des.path.work={{ tmpDir }} -Des.path.plugins={{ homeDir }}/plugins"'
  
- name: Register service
  command: /sbin/chkconfig --add elasticsearch
  
- name: Install Marvel
  command: /usr/share/elasticsearch/bin/plugin -i elasticsearch/marvel/latest creates=/usr/share/elasticsearch/plugins/marvel

- name: Install AWS Plugin
  command: /usr/share/elasticsearch/bin/plugin -i elasticsearch/elasticsearch-cloud-aws/2.1.1 creates=/usr/share/elasticsearch/plugins/cloud-aws

- name: Upload Config
  copy: src=elasticsearch.yml dest=/etc/elasticsearch/  

- name: Restart Elasticsearch
  service: name=elasticsearch state=restarted
  